import { Raleway } from "next/font/google";
import Navbar from "@widgets/Navbar";
import "@styles/main.scss";
import Footer from "@widgets/Footer";
import styles from '@styles/scss/home.module.scss'
import { Toaster } from "react-hot-toast";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "NCIPETC'24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/images/clogo.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <Toaster position="bottom-center" />
        <div className={styles.homeContainer}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
